name: instagram
description: "An Instagram Frontend App in Flutter Development."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  lordicon: ^1.0.3
  google_fonts: ^6.2.1
  screenshot: ^2.3.0
  flutter_share: ^2.0.0
  provider: ^6.1.2
  path_provider: ^2.1.2
  path: ^1.8.2
  fluttertoast: ^8.2.1
  share: ^2.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

